# Generated by Django 5.1.2 on 2024-11-03 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_examenes', '0009_alter_examen_planificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='autenticacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reconocimientofacial', models.BooleanField(default=False, verbose_name='Reconocimiento facial')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario autenticado')),
            ],
        ),
    ]
