# Generated by Django 5.1.2 on 2024-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.IntegerField()),
                ('fechainicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicial')),
                ('fechafinal', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
