# Generated by Django 5.1.2 on 2024-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_examenes', '0005_planificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(verbose_name='Fecha inicial')),
                ('fechafinal', models.DateField(verbose_name='Fecha final')),
                ('cantidadpreguntas', models.IntegerField(verbose_name='Cantidad de preguntas')),
                ('duracion', models.DurationField(help_text='Duración del examen')),
                ('nintentos', models.IntegerField(verbose_name='Numero de intentos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
