# Generated by Django 5.1.2 on 2024-11-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_examenes', '0006_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='duracion',
            field=models.DurationField(help_text='Duración del examen en minutos'),
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.examen')),
            ],
        ),
    ]
