# Generated by Django 5.1.2 on 2024-11-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_examenes', '0007_alter_examen_duracion_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='planificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.planificacion'),
        ),
    ]
