# Generated by Django 5.1.2 on 2024-11-03 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_examenes', '0008_examen_planificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.planificacion'),
        ),
    ]
