# Generated by Django 5.1.2 on 2024-11-21 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_examenes', '0010_opcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='respuestaexamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_examenes.pregunta')),
                ('respuesta_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='gestion_examenes.respuestaexamen')),
            ],
        ),
    ]
